# Generated by Django 2.2.4 on 2021-03-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner_flats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='name',
        ),
    ]
