# Generated by Django 2.2.4 on 2021-03-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20210322_1058'),
    ]

    operations = [
    ]
