# Generated by Django 2.2.4 on 2021-03-22 08:11

from django.db import migrations


def add_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner = {
            'name': flat.owner,
            'phonenumber': flat.owners_phonenumber,
            'pure_phone': flat.owner_pure_phone
        }
        Owner.objects.get_or_create(
            name=flat.owner, 
            pure_phone=flat.owner_pure_phone, 
            defaults={
            'phonenumber': flat.owners_phonenumber,
            }
        )


def backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20210322_1111'),
    ]

    operations = [
        migrations.RunPython(add_owners, backward)
    ]
