# Generated by Django 2.2.4 on 2021-03-22 08:47

from django.db import migrations

def set_flat_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.all():
        owners_flats = Flat.objects.filter(
            owner=owner.name,
            owner_pure_phone=owner.pure_phone
        )
        current_owner, created = Owner.objects.update_or_create(
            name=owner.name,
            pure_phone=owner.pure_phone,
            defaults={
                'phonenumber': owner.phonenumber,
            }
        )
        if not created:
            current_owner.flats.set(owners_flats)

def backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.flats.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20210322_1147'),
    ]

    operations = [
        migrations.RunPython(set_flat_owner, backward)
    ]
